# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 05:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('path', models.CharField(blank=True, max_length=200, null=True)),
                ('complete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '\u56de\u7b54\u9879',
                'verbose_name_plural': '\u56de\u7b54\u9879',
            },
        ),
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('finished', models.BooleanField(default=False)),
                ('complete_cnt', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '\u95ee\u5377',
                'verbose_name_plural': '\u95ee\u5377',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u7701\u4efd',
                'verbose_name_plural': '\u7701\u4efd',
            },
        ),
        migrations.CreateModel(
            name='QuestionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('index', models.IntegerField()),
            ],
            options={
                'verbose_name': '\u95ee\u9898\u9879',
                'verbose_name_plural': '\u95ee\u9898\u9879',
            },
        ),
        migrations.CreateModel(
            name='QuestionSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '\u95ee\u5377',
                'verbose_name_plural': '\u95ee\u5377',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='const.Province')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u9662\u6821',
                'verbose_name_plural': '\u9662\u6821',
            },
        ),
        migrations.AddField(
            model_name='questionitem',
            name='question_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='const.QuestionSheet'),
        ),
        migrations.AddField(
            model_name='answersheet',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='const.School'),
        ),
        migrations.AddField(
            model_name='answeritem',
            name='answer_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='const.AnswerSheet'),
        ),
        migrations.AddField(
            model_name='answeritem',
            name='question_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='const.QuestionItem'),
        ),
    ]
