# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('const', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answersheet',
            options={'verbose_name': '\u7b54\u5377', 'verbose_name_plural': '\u7b54\u5377'},
        ),
        migrations.AlterField(
            model_name='questionsheet',
            name='category',
            field=models.CharField(blank=True, choices=[((b'0', '\u7701\u95ee\u5377'), (b'1', '\u6821\u95ee\u5377'))], default='0', max_length=20),
        ),
    ]
