# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('const', '0002_auto_20161129_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersheet',
            name='question_sheet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='const.QuestionSheet'),
        ),
        migrations.AlterField(
            model_name='questionsheet',
            name='category',
            field=models.CharField(choices=[(b'0', '\u7701\u95ee\u5377'), (b'1', '\u6821\u95ee\u5377')], max_length=20),
        ),
    ]
