# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 03:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('const', '0003_auto_20161129_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answersheet',
            name='school',
        ),
        migrations.RemoveField(
            model_name='answersheet',
            name='year',
        ),
        migrations.AddField(
            model_name='answersheet',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
