# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('const', '0004_auto_20161129_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answeritem',
            name='number',
        ),
        migrations.AddField(
            model_name='answeritem',
            name='value',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='answeritem',
            name='path',
            field=models.CharField(default='', max_length=200),
        ),
    ]
