# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('const', '0005_auto_20161129_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeritem',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='province',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='questionitem',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='questionsheet',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='school',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=40, primary_key=True, serialize=False),
        ),
    ]
