# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('const', '0006_auto_20161129_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answeritem',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='answersheet',
            name='complete_cnt',
        ),
        migrations.AddField(
            model_name='questionitem',
            name='text_for_manager',
            field=models.CharField(default='Not Set Yet', max_length=200),
            preserve_default=False,
        ),
    ]
