# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('const', '0007_auto_20161129_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeritem',
            name='boolean_input',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
